"""Update Associations

Revision ID: 2a5654926eb2
Revises: 9ad647ce5541
Create Date: 2022-02-07 19:20:07.731119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5654926eb2'
down_revision = '9ad647ce5541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
