"""Add Role

Revision ID: 2c5f0f7a9cbb
Revises: 2a5654926eb2
Create Date: 2022-02-17 18:17:05.646659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5f0f7a9cbb'
down_revision = '2a5654926eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
