"""user - mentorship

Revision ID: 389325df5b41
Revises: b270fcf3d2e8
Create Date: 2022-02-18 20:20:59.898756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389325df5b41'
down_revision = 'b270fcf3d2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorship_requests', sa.Column('technology_used', sa.String(), nullable=True))
    op.add_column('mentorship_requests', sa.Column('urgency', sa.Integer(), nullable=True))
    op.add_column('mentorship_requests', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('mentorship_requests', sa.Column('participant_user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_mentorship_requests_description', table_name='mentorship_requests')
    op.create_index(op.f('ix_mentorship_requests_urgency'), 'mentorship_requests', ['urgency'], unique=False)
    op.create_foreign_key(None, 'mentorship_requests', 'users', ['participant_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentorship_requests', type_='foreignkey')
    op.drop_index(op.f('ix_mentorship_requests_urgency'), table_name='mentorship_requests')
    op.create_index('ix_mentorship_requests_description', 'mentorship_requests', ['description'], unique=False)
    op.drop_column('mentorship_requests', 'participant_user_id')
    op.drop_column('mentorship_requests', 'image_url')
    op.drop_column('mentorship_requests', 'urgency')
    op.drop_column('mentorship_requests', 'technology_used')
    # ### end Alembic commands ###
