"""Add back_populates role

Revision ID: 40fe82b2bb48
Revises: f6d4cbefe90f
Create Date: 2022-02-17 20:08:20.189448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fe82b2bb48'
down_revision = 'f6d4cbefe90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
