"""Add Mentor and User IDs to Mentorship

Revision ID: 4f37d5c40709
Revises: 389325df5b41
Create Date: 2022-02-18 20:27:19.445394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f37d5c40709'
down_revision = '389325df5b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorship_requests', sa.Column('mentor_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mentorship_requests', 'users', ['mentor_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentorship_requests', type_='foreignkey')
    op.drop_column('mentorship_requests', 'mentor_user_id')
    # ### end Alembic commands ###
