"""Add Additional Fields

Revision ID: 9ad647ce5541
Revises: 99391897ba61
Create Date: 2022-02-07 18:52:16.180363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad647ce5541'
down_revision = '99391897ba61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_PrizeProjectWinnerMapping_id', table_name='PrizeProjectWinnerMapping')
    op.drop_table('PrizeProjectWinnerMapping')
    op.add_column('prizes', sa.Column('reward', sa.String(), nullable=True))
    op.add_column('prizes', sa.Column('sponsor', sa.String(), nullable=True))
    op.add_column('prizes', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('prizes', sa.Column('selectable', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_prizes_priority'), 'prizes', ['priority'], unique=False)
    op.create_index(op.f('ix_prizes_reward'), 'prizes', ['reward'], unique=False)
    op.create_index(op.f('ix_prizes_selectable'), 'prizes', ['selectable'], unique=False)
    op.create_index(op.f('ix_prizes_sponsor'), 'prizes', ['sponsor'], unique=False)
    op.drop_constraint('prizes_owner_id_fkey', 'prizes', type_='foreignkey')
    op.drop_column('prizes', 'owner_id')
    op.add_column('users', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_token_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'project_id')
    op.drop_column('users', 'password_reset_token_sent_at')
    op.drop_column('users', 'password_reset_token')
    op.add_column('prizes', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('prizes_owner_id_fkey', 'prizes', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_prizes_sponsor'), table_name='prizes')
    op.drop_index(op.f('ix_prizes_selectable'), table_name='prizes')
    op.drop_index(op.f('ix_prizes_reward'), table_name='prizes')
    op.drop_index(op.f('ix_prizes_priority'), table_name='prizes')
    op.drop_column('prizes', 'selectable')
    op.drop_column('prizes', 'priority')
    op.drop_column('prizes', 'sponsor')
    op.drop_column('prizes', 'reward')
    op.create_table('PrizeProjectWinnerMapping',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"PrizeProjectWinnerMapping_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prizeId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prizeId'], ['prizes.id'], name='PrizeProjectWinnerMapping_prizeId_fkey'),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], name='PrizeProjectWinnerMapping_projectId_fkey'),
    sa.PrimaryKeyConstraint('id', name='PrizeProjectWinnerMapping_pkey')
    )
    op.create_index('ix_PrizeProjectWinnerMapping_id', 'PrizeProjectWinnerMapping', ['id'], unique=False)
    # ### end Alembic commands ###
