"""Mentorship update

Revision ID: 9d1d7de2aa0d
Revises: 4f37d5c40709
Create Date: 2022-02-18 20:53:26.160415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1d7de2aa0d'
down_revision = '4f37d5c40709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorship_requests', sa.Column('resolved', sa.Boolean(), nullable=True))
    op.drop_index('ix_mentorship_requests_title', table_name='mentorship_requests')
    op.create_index(op.f('ix_mentorship_requests_title'), 'mentorship_requests', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentorship_requests_title'), table_name='mentorship_requests')
    op.create_index('ix_mentorship_requests_title', 'mentorship_requests', ['title'], unique=False)
    op.drop_column('mentorship_requests', 'resolved')
    # ### end Alembic commands ###
