"""Update Project Fields

Revision ID: a443cca33715
Revises: 76d30d6bccdf
Create Date: 2022-02-18 15:35:33.362496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a443cca33715'
down_revision = '76d30d6bccdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('inspiration', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('functionality', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('architecture', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('technologiesUsed', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('challengesFaced', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('lessonsLearned', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('nextSteps', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('inPersonProject', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('requiresPowerOutlet', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'requiresPowerOutlet')
    op.drop_column('projects', 'inPersonProject')
    op.drop_column('projects', 'nextSteps')
    op.drop_column('projects', 'lessonsLearned')
    op.drop_column('projects', 'challengesFaced')
    op.drop_column('projects', 'technologiesUsed')
    op.drop_column('projects', 'architecture')
    op.drop_column('projects', 'functionality')
    op.drop_column('projects', 'inspiration')
    # ### end Alembic commands ###
