"""Update prize project associations

Revision ID: b270fcf3d2e8
Revises: a443cca33715
Create Date: 2022-02-18 19:24:24.289835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b270fcf3d2e8'
down_revision = 'a443cca33715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prize_project_winner_map_id', table_name='prize_project_winner_map')
    op.drop_table('prize_project_winner_map')
    op.drop_table('association')
    op.drop_index('ix_prize_project_attempt_map_id', table_name='prize_project_attempt_map')
    op.drop_table('prize_project_attempt_map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prize_project_attempt_map',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prizeId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prizeId'], ['prizes.id'], name='prize_project_attempt_map_prizeId_fkey'),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], name='prize_project_attempt_map_projectId_fkey'),
    sa.PrimaryKeyConstraint('id', name='prize_project_attempt_map_pkey')
    )
    op.create_index('ix_prize_project_attempt_map_id', 'prize_project_attempt_map', ['id'], unique=False)
    op.create_table('association',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prize_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prize_id'], ['prizes.id'], name='association_prize_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='association_project_id_fkey')
    )
    op.create_table('prize_project_winner_map',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prizeId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prizeId'], ['prizes.id'], name='prize_project_winner_map_prizeId_fkey'),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], name='prize_project_winner_map_projectId_fkey'),
    sa.PrimaryKeyConstraint('id', name='prize_project_winner_map_pkey')
    )
    op.create_index('ix_prize_project_winner_map_id', 'prize_project_winner_map', ['id'], unique=False)
    # ### end Alembic commands ###
