"""Additional role

Revision ID: f6d4cbefe90f
Revises: 2c5f0f7a9cbb
Create Date: 2022-02-17 19:38:59.091381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d4cbefe90f'
down_revision = '2c5f0f7a9cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
